-- Add food preference columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS dietary_restrictions TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS cuisine_preferences TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS disliked_foods TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS cooking_level TEXT DEFAULT 'moderate';

-- Create meal_recipes table
CREATE TABLE IF NOT EXISTS meal_recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  cuisine TEXT NOT NULL,
  meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast','lunch','dinner','snack')),
  calories INTEGER NOT NULL,
  protein INTEGER NOT NULL,
  carbs INTEGER NOT NULL,
  fat INTEGER NOT NULL,
  description TEXT NOT NULL,
  dietary_tags TEXT[] DEFAULT '{}',
  main_protein TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE meal_recipes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'meal_recipes' AND policyname = 'meal_recipes_read_all'
  ) THEN
    CREATE POLICY "meal_recipes_read_all" ON meal_recipes FOR SELECT USING (true);
  END IF;
END $$;

-- Seed 100 diverse recipes
INSERT INTO meal_recipes (name, cuisine, meal_type, calories, protein, carbs, fat, description, dietary_tags, main_protein) VALUES
('Shakshuka', 'Middle Eastern', 'breakfast', 380, 22, 28, 18, 'Poached eggs in a spiced tomato and pepper sauce with warm pita', ARRAY['vegetarian'], 'eggs'),
('Caprese Frittata', 'Italian', 'breakfast', 340, 24, 8, 24, 'Baked egg frittata with fresh mozzarella, tomatoes, and basil', ARRAY['vegetarian','gluten-free'], 'eggs'),
('Chilaquiles Rojos', 'Mexican', 'breakfast', 450, 20, 48, 18, 'Crispy tortilla chips simmered in red salsa topped with crema and cotija', ARRAY['vegetarian'], 'eggs'),
('Miso Soup with Tamago Gohan', 'Japanese', 'breakfast', 310, 18, 42, 7, 'Steamed rice topped with a raw egg and soy sauce alongside miso soup', ARRAY[]::text[], 'eggs'),
('Avocado Toast with Dukkah', 'Mediterranean', 'breakfast', 390, 12, 38, 22, 'Sourdough toast with smashed avocado, poached egg, and Egyptian nut-spice blend', ARRAY['vegetarian'], 'eggs'),
('Congee with Century Egg', 'Asian', 'breakfast', 280, 14, 44, 5, 'Silky rice porridge with century egg, ginger, and crispy shallots', ARRAY['gluten-free'], 'eggs'),
('Huevos Rancheros', 'Mexican', 'breakfast', 420, 22, 36, 20, 'Fried eggs on corn tortillas with black beans, salsa verde, and queso fresco', ARRAY['vegetarian','gluten-free'], 'eggs'),
('Acai Bowl with Granola', 'American', 'breakfast', 460, 10, 72, 14, 'Thick blended acai with banana, topped with granola, coconut flakes, and fresh berries', ARRAY['vegan','dairy-free'], 'none'),
('Korean Egg Toast', 'Korean', 'breakfast', 350, 16, 38, 14, 'Fluffy egg-stuffed bread roll with sweet mayo and ketchup drizzle', ARRAY[]::text[], 'eggs'),
('Ful Medames', 'Middle Eastern', 'breakfast', 360, 18, 52, 8, 'Slow-cooked fava beans with lemon, cumin, and olive oil served with flatbread', ARRAY['vegan','gluten-free'], 'legumes'),
('Masala Omelette', 'Indian', 'breakfast', 320, 20, 10, 22, 'Spiced omelette with onions, green chili, tomatoes, and fresh coriander', ARRAY['vegetarian','gluten-free'], 'eggs'),
('Smoked Salmon Bagel', 'American', 'breakfast', 480, 28, 44, 18, 'Everything bagel with cream cheese, smoked salmon, capers, and red onion', ARRAY[]::text[], 'salmon'),
('Tamagoyaki with Dashi Rice', 'Japanese', 'breakfast', 330, 16, 40, 10, 'Sweet rolled Japanese omelette served over dashi-seasoned rice', ARRAY['gluten-free'], 'eggs'),
('Arepas con Queso', 'Caribbean', 'breakfast', 400, 14, 52, 16, 'Griddled cornmeal cakes stuffed with melted white cheese', ARRAY['vegetarian','gluten-free'], 'cheese'),
('Overnight Oats with Mango Lassi', 'Indian', 'breakfast', 420, 16, 68, 10, 'Cardamom-spiced overnight oats topped with mango lassi drizzle and pistachios', ARRAY['vegetarian'], 'yogurt'),
('Bao Bun with Pork Belly', 'Asian', 'breakfast', 440, 22, 50, 16, 'Steamed fluffy bao filled with braised pork belly, pickled daikon, and hoisin', ARRAY[]::text[], 'pork'),
('Greek Yogurt Parfait', 'Mediterranean', 'breakfast', 380, 18, 46, 14, 'Thick Greek yogurt layered with honey, walnuts, and crushed baklava crumble', ARRAY['vegetarian'], 'yogurt'),
('Breakfast Burrito', 'Mexican', 'breakfast', 520, 28, 48, 22, 'Flour tortilla stuffed with chorizo, scrambled eggs, peppers, and pepper jack cheese', ARRAY[]::text[], 'chorizo'),
('Idli Sambar', 'Indian', 'breakfast', 340, 12, 58, 6, 'Steamed rice and lentil cakes served with spiced lentil soup and coconut chutney', ARRAY['vegan','gluten-free'], 'lentils'),
('Jianbing Chinese Crepe', 'Asian', 'breakfast', 390, 16, 48, 14, 'Crispy Chinese street crepe with egg, hoisin, scallions, and crispy wonton', ARRAY[]::text[], 'eggs'),
('Pao de Queijo with Fruit', 'American', 'breakfast', 350, 10, 44, 16, 'Brazilian cheese bread rolls served with fresh tropical fruit salad', ARRAY['vegetarian','gluten-free'], 'cheese'),
('Shakshuka Verde', 'Middle Eastern', 'breakfast', 360, 20, 22, 20, 'Eggs poached in a vibrant green tomatillo and herb sauce with feta', ARRAY['vegetarian','gluten-free'], 'eggs'),
('Bircher Muesli', 'Mediterranean', 'breakfast', 410, 14, 62, 12, 'Swiss-style overnight oats with apple, hazelnuts, and yogurt', ARRAY['vegetarian'], 'yogurt'),
('Tteok-bokki Breakfast Bowl', 'Korean', 'breakfast', 430, 18, 60, 12, 'Spicy rice cakes with soft-boiled egg, fish cake, and gochujang broth', ARRAY[]::text[], 'eggs'),
('Menemen', 'Middle Eastern', 'breakfast', 340, 16, 18, 22, 'Turkish scrambled eggs with tomatoes, green peppers, and spices in a cast iron pan', ARRAY['vegetarian','gluten-free'], 'eggs'),
('Bibimbap', 'Korean', 'lunch', 520, 28, 68, 14, 'Warm rice bowl with seasoned vegetables, gochujang, and a fried egg', ARRAY['gluten-free'], 'eggs'),
('Tacos al Pastor', 'Mexican', 'lunch', 580, 32, 52, 22, 'Marinated pork tacos with pineapple, cilantro, and salsa verde on corn tortillas', ARRAY['gluten-free'], 'pork'),
('Pad Thai', 'Asian', 'lunch', 560, 26, 72, 16, 'Stir-fried rice noodles with shrimp, bean sprouts, peanuts, and tamarind sauce', ARRAY[]::text[], 'shrimp'),
('Falafel Wrap', 'Middle Eastern', 'lunch', 490, 18, 62, 18, 'Crispy falafel in flatbread with hummus, tabbouleh, and pickled turnips', ARRAY['vegan'], 'legumes'),
('Butter Chicken with Naan', 'Indian', 'lunch', 620, 38, 52, 24, 'Tender chicken in a rich tomato-cream sauce with garlic naan', ARRAY[]::text[], 'chicken'),
('Carne Asada Bowl', 'Mexican', 'lunch', 590, 42, 48, 22, 'Grilled marinated beef over cilantro rice with pico de gallo and guacamole', ARRAY['gluten-free'], 'beef'),
('Ramen Tonkotsu', 'Japanese', 'lunch', 640, 34, 72, 22, 'Rich pork bone broth ramen with chashu pork, soft egg, nori, and bamboo shoots', ARRAY[]::text[], 'pork'),
('Dal Makhani', 'Indian', 'lunch', 480, 22, 62, 14, 'Slow-cooked black lentils in a buttery tomato sauce with cream and spices', ARRAY['vegetarian'], 'lentils'),
('Mapo Tofu', 'Asian', 'lunch', 440, 24, 28, 24, 'Silken tofu in a fiery Sichuan sauce with ground pork and numbing peppercorns', ARRAY[]::text[], 'pork'),
('Jerk Chicken with Rice and Peas', 'Caribbean', 'lunch', 610, 44, 58, 18, 'Scotch bonnet-marinated jerk chicken with coconut rice and kidney beans', ARRAY['gluten-free'], 'chicken'),
('Miso-Glazed Salmon Donburi', 'Japanese', 'lunch', 540, 36, 58, 16, 'Miso-marinated salmon over steamed rice with pickled cucumber and sesame', ARRAY['gluten-free'], 'salmon'),
('Lamb Shawarma Plate', 'Middle Eastern', 'lunch', 580, 38, 44, 24, 'Spiced lamb shawarma with hummus, fattoush salad, and warm pita', ARRAY[]::text[], 'lamb'),
('Palak Paneer', 'Indian', 'lunch', 460, 22, 32, 28, 'Fresh paneer cubes in a creamy spiced spinach sauce with basmati rice', ARRAY['vegetarian','gluten-free'], 'paneer'),
('Korean Bulgogi Bowl', 'Korean', 'lunch', 550, 36, 56, 18, 'Sweet soy-marinated beef over rice with kimchi, pickled radish, and sesame spinach', ARRAY['gluten-free'], 'beef'),
('Chicken Souvlaki Pita', 'Mediterranean', 'lunch', 520, 38, 46, 16, 'Grilled chicken skewers in warm pita with tzatziki, tomatoes, and red onion', ARRAY[]::text[], 'chicken'),
('Pozole Rojo', 'Mexican', 'lunch', 480, 32, 52, 12, 'Slow-cooked pork and hominy soup with shredded cabbage, radish, and lime', ARRAY['gluten-free'], 'pork'),
('Beef Rendang', 'Asian', 'lunch', 560, 38, 22, 36, 'Slow-braised beef in coconut milk with lemongrass, galangal, and kaffir lime', ARRAY['gluten-free','dairy-free'], 'beef'),
('Galbi Korean Short Ribs', 'Korean', 'lunch', 620, 40, 32, 38, 'Marinated beef short ribs with steamed rice, banchan, and doenjang soup', ARRAY['gluten-free'], 'beef'),
('Osso Buco with Gremolata', 'Italian', 'lunch', 580, 44, 28, 28, 'Braised veal shanks in white wine with saffron risotto and lemon gremolata', ARRAY['gluten-free'], 'veal'),
('Chicken Tikka Masala', 'Indian', 'lunch', 540, 40, 38, 22, 'Charred chicken in a velvety spiced tomato-cream sauce with basmati rice', ARRAY['gluten-free'], 'chicken'),
('Tuna Poke Bowl', 'Asian', 'lunch', 490, 34, 52, 14, 'Sushi-grade tuna with edamame, avocado, cucumber, and spicy mayo over rice', ARRAY['gluten-free','dairy-free'], 'tuna'),
('Moussaka', 'Mediterranean', 'lunch', 560, 30, 36, 30, 'Layered eggplant and spiced lamb with bechamel sauce, baked golden', ARRAY[]::text[], 'lamb'),
('Enchiladas Verdes', 'Mexican', 'lunch', 520, 32, 48, 20, 'Corn tortillas filled with chicken, smothered in tomatillo sauce and melted cheese', ARRAY['gluten-free'], 'chicken'),
('Oxtail Stew with Rice', 'Caribbean', 'lunch', 640, 46, 48, 24, 'Slow-braised oxtail in a rich brown stew with butter beans and white rice', ARRAY['gluten-free','dairy-free'], 'beef'),
('Soba Noodle Bowl', 'Japanese', 'lunch', 420, 22, 62, 8, 'Cold buckwheat noodles with dashi broth, tempura shrimp, and scallions', ARRAY['dairy-free'], 'shrimp'),
('Lamb Kofta Plate', 'Middle Eastern', 'lunch', 530, 36, 38, 24, 'Spiced lamb meatballs with saffron rice, roasted eggplant, and tahini', ARRAY['gluten-free'], 'lamb'),
('Pasta e Fagioli', 'Italian', 'lunch', 480, 20, 68, 12, 'Rustic Italian pasta and bean soup with rosemary, pancetta, and Parmesan', ARRAY[]::text[], 'legumes'),
('Adobo Chicken', 'Asian', 'lunch', 510, 40, 28, 24, 'Filipino chicken braised in vinegar, soy, garlic, and bay leaves with rice', ARRAY['gluten-free','dairy-free'], 'chicken'),
('Chana Masala', 'Indian', 'lunch', 440, 18, 62, 12, 'Spiced chickpea curry with tomatoes, onions, and fresh ginger over basmati', ARRAY['vegan','gluten-free'], 'legumes'),
('Ceviche Tostadas', 'Mexican', 'lunch', 380, 28, 36, 10, 'Fresh lime-cured shrimp ceviche on crispy tostadas with avocado and jalapeno', ARRAY['gluten-free','dairy-free'], 'shrimp'),
('Miso-Glazed Black Cod', 'Japanese', 'dinner', 480, 36, 22, 24, 'Buttery black cod marinated in white miso and mirin, broiled until caramelized', ARRAY['gluten-free','dairy-free'], 'fish'),
('Lamb Tagine with Preserved Lemon', 'Middle Eastern', 'dinner', 560, 38, 42, 22, 'Slow-cooked lamb with olives, preserved lemon, and couscous', ARRAY['dairy-free'], 'lamb'),
('Beef Bulgogi Hotpot', 'Korean', 'dinner', 580, 42, 44, 22, 'Sizzling marinated beef in a tabletop hotpot with glass noodles and vegetables', ARRAY['dairy-free'], 'beef'),
('Chicken Mole Negro', 'Mexican', 'dinner', 560, 40, 38, 24, 'Chicken braised in a complex dark mole with chocolate, chilies, and spices', ARRAY['gluten-free','dairy-free'], 'chicken'),
('Lamb Rogan Josh', 'Indian', 'dinner', 540, 40, 28, 28, 'Kashmiri-style lamb curry with whole spices, yogurt, and fragrant basmati', ARRAY['gluten-free'], 'lamb'),
('Peking Duck Pancakes', 'Asian', 'dinner', 580, 34, 48, 26, 'Crispy roasted duck with hoisin, cucumber, and scallions in thin pancakes', ARRAY['dairy-free'], 'duck'),
('Seafood Paella', 'Mediterranean', 'dinner', 560, 36, 62, 14, 'Saffron-infused rice with shrimp, mussels, squid, and chorizo', ARRAY['gluten-free','dairy-free'], 'seafood'),
('Galbi Jjim Braised Short Ribs', 'Korean', 'dinner', 640, 46, 36, 36, 'Slow-braised beef short ribs in sweet soy sauce with chestnuts and jujubes', ARRAY['gluten-free','dairy-free'], 'beef'),
('Osso Buco alla Milanese', 'Italian', 'dinner', 600, 48, 24, 32, 'Braised veal shanks with saffron risotto, gremolata, and bone marrow', ARRAY['gluten-free'], 'veal'),
('Palak Paneer with Garlic Naan', 'Indian', 'dinner', 520, 24, 48, 24, 'Creamy spinach curry with paneer, served with buttery garlic naan', ARRAY['vegetarian'], 'paneer'),
('Jerk Pork Tenderloin', 'Caribbean', 'dinner', 480, 44, 22, 22, 'Scotch bonnet and allspice-rubbed pork with festival dumplings and mango salsa', ARRAY['gluten-free','dairy-free'], 'pork'),
('Sushi Omakase Bowl', 'Japanese', 'dinner', 520, 32, 62, 14, 'Chef-style assorted sashimi over seasoned sushi rice with pickled ginger', ARRAY['gluten-free','dairy-free'], 'fish'),
('Carne Asada Tacos', 'Mexican', 'dinner', 560, 40, 44, 22, 'Charred skirt steak tacos with charred scallions, salsa roja, and lime crema', ARRAY['gluten-free'], 'beef'),
('Chicken Shawarma Platter', 'Middle Eastern', 'dinner', 540, 42, 38, 22, 'Spiced rotisserie chicken with garlic sauce, fattoush, and warm flatbread', ARRAY[]::text[], 'chicken'),
('Beef Rendang with Coconut Rice', 'Asian', 'dinner', 620, 42, 48, 28, 'Dry-fried beef rendang with fragrant coconut rice and cucumber achar', ARRAY['gluten-free','dairy-free'], 'beef'),
('Grilled Branzino with Chermoula', 'Mediterranean', 'dinner', 420, 38, 12, 22, 'Whole grilled sea bass with North African herb sauce and roasted vegetables', ARRAY['gluten-free','dairy-free'], 'fish'),
('Butter Chicken Biryani', 'Indian', 'dinner', 640, 42, 68, 22, 'Layered basmati rice with butter chicken, caramelized onions, and saffron', ARRAY['gluten-free'], 'chicken'),
('Mapo Tofu with Pork', 'Asian', 'dinner', 480, 28, 32, 26, 'Silken tofu in a fiery Sichuan doubanjiang sauce with minced pork and rice', ARRAY['gluten-free','dairy-free'], 'pork'),
('Lamb Kofta with Saffron Rice', 'Middle Eastern', 'dinner', 560, 38, 44, 24, 'Grilled spiced lamb meatballs with saffron pilaf, roasted tomatoes, and tahini', ARRAY['gluten-free','dairy-free'], 'lamb'),
('Pasta Carbonara', 'Italian', 'dinner', 580, 28, 62, 24, 'Silky egg and Pecorino sauce with guanciale and black pepper on rigatoni', ARRAY[]::text[], 'pork'),
('Tteok-bokki with Ramen', 'Korean', 'dinner', 520, 22, 72, 14, 'Spicy rice cakes and ramen noodles in gochujang broth with fish cake and egg', ARRAY[]::text[], 'eggs'),
('Cochinita Pibil', 'Mexican', 'dinner', 540, 40, 36, 24, 'Achiote-marinated slow-roasted pork with pickled red onions and habanero salsa', ARRAY['gluten-free','dairy-free'], 'pork'),
('Grilled Octopus with Romesco', 'Mediterranean', 'dinner', 440, 36, 22, 20, 'Charred octopus with smoky Catalan romesco sauce and white bean salad', ARRAY['gluten-free','dairy-free'], 'seafood'),
('Chicken Katsu Curry', 'Japanese', 'dinner', 620, 38, 72, 18, 'Crispy panko chicken cutlet with Japanese curry sauce and steamed rice', ARRAY['dairy-free'], 'chicken'),
('Goat Curry with Roti', 'Caribbean', 'dinner', 580, 44, 42, 24, 'Slow-cooked curried goat with scotch bonnet, potatoes, and flaky roti', ARRAY['dairy-free'], 'goat'),
('Saag Gosht', 'Indian', 'dinner', 520, 42, 22, 28, 'Slow-cooked lamb in a rich spinach and spice gravy with basmati rice', ARRAY['gluten-free'], 'lamb'),
('Linguine alle Vongole', 'Italian', 'dinner', 480, 28, 62, 14, 'Linguine with fresh clams in white wine, garlic, and parsley sauce', ARRAY['dairy-free'], 'seafood'),
('Dakgalbi Spicy Korean Chicken', 'Korean', 'dinner', 500, 40, 38, 18, 'Stir-fried spicy chicken with rice cakes, cabbage, and sweet potato in gochujang', ARRAY['gluten-free','dairy-free'], 'chicken'),
('Chicken Tikka Masala Dinner', 'Indian', 'dinner', 480, 38, 22, 24, 'Tender chicken in a rich creamy tomato-based sauce with basmati rice', ARRAY[]::text[], 'chicken'),
('Mango Lassi with Pistachios', 'Indian', 'snack', 220, 8, 36, 6, 'Thick blended mango and yogurt drink topped with crushed pistachios', ARRAY['vegetarian','gluten-free'], 'yogurt'),
('Edamame with Togarashi', 'Japanese', 'snack', 180, 14, 14, 6, 'Steamed edamame pods dusted with Japanese seven-spice blend', ARRAY['vegan','gluten-free'], 'legumes'),
('Guacamole with Plantain Chips', 'Mexican', 'snack', 280, 4, 32, 16, 'Fresh chunky guacamole with crispy baked plantain chips', ARRAY['vegan','gluten-free'], 'none'),
('Hummus with Zaatar Pita', 'Middle Eastern', 'snack', 260, 10, 32, 10, 'Creamy hummus drizzled with olive oil and zaatar with warm pita triangles', ARRAY['vegan'], 'legumes'),
('Korean Corn Dog', 'Korean', 'snack', 320, 12, 38, 14, 'Crispy battered hot dog on a stick with mustard and ketchup drizzle', ARRAY[]::text[], 'pork'),
('Acai Energy Bites', 'American', 'snack', 200, 6, 28, 8, 'No-bake acai and oat energy balls with dark chocolate chips and coconut', ARRAY['vegan','gluten-free'], 'none'),
('Spanakopita Triangles', 'Mediterranean', 'snack', 240, 8, 22, 14, 'Crispy phyllo pastry filled with spinach and feta cheese', ARRAY['vegetarian'], 'cheese'),
('Onigiri Rice Ball', 'Japanese', 'snack', 200, 8, 36, 2, 'Hand-pressed rice ball filled with spicy tuna and wrapped in nori', ARRAY['gluten-free','dairy-free'], 'tuna'),
('Samosa with Mint Chutney', 'Indian', 'snack', 280, 6, 36, 12, 'Crispy pastry filled with spiced potato and peas, served with fresh mint chutney', ARRAY['vegan'], 'legumes'),
('Tostones with Black Bean Dip', 'Caribbean', 'snack', 260, 8, 38, 8, 'Twice-fried green plantains with a smoky black bean and lime dip', ARRAY['vegan','gluten-free'], 'legumes'),
('Bao Bun with Char Siu', 'Asian', 'snack', 300, 14, 42, 8, 'Fluffy steamed bao filled with sweet BBQ pork and pickled vegetables', ARRAY['dairy-free'], 'pork'),
('Labneh with Olive Oil', 'Middle Eastern', 'snack', 200, 10, 8, 16, 'Strained yogurt cheese rolled in zaatar and chili flakes with flatbread', ARRAY['vegetarian'], 'yogurt'),
('Elote Mexican Street Corn', 'Mexican', 'snack', 240, 6, 32, 10, 'Grilled corn on the cob slathered with mayo, cotija cheese, chili, and lime', ARRAY['vegetarian','gluten-free'], 'none'),
('Kimchi Pancake', 'Korean', 'snack', 260, 8, 34, 10, 'Crispy savory pancake loaded with fermented kimchi and scallions', ARRAY['vegan','dairy-free'], 'none'),
('Caprese Skewers', 'Italian', 'snack', 200, 10, 6, 16, 'Fresh mozzarella, cherry tomatoes, and basil drizzled with balsamic glaze', ARRAY['vegetarian','gluten-free'], 'cheese');
